filter:
    excluded_paths: [vendor/*, app/*, web/*]

before_commands:
    - "composer install --prefer-source"

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_code_coverage: true
    php_mess_detector: true
    sensiolabs_security_checker: true
